"""Generate the gold set: python -m intake.synth

Writes data/gold/v1/cases.yaml (labels) and data/gold/v1/pdfs/*.pdf (documents). Seeded, so
re-running reproduces the same identities and labels.
"""

import sys

import yaml

from intake.eval.gold import GoldSet, gold_dir
from intake.settings import get_settings
from intake.synth.build import GOLD_VERSION, SEED, build_requisitions
from intake.synth.render import write_case_pdf

HEADER = """\
# gold.v1: 60 synthetic requisitions with gold labels. FROZEN: new cases go into gold.v2.
# Generated by `python -m intake.synth` from intake/synth/scenarios.py (do not edit by hand).
# Priority and protocol labels were set by the author against data/rubric.md; they have not
# been reviewed by a radiologist. All names, numbers and clinical details are fictional.
"""


def main() -> int:
    out_dir = gold_dir(get_settings().data_dir, GOLD_VERSION)
    requisitions = build_requisitions()
    gold = GoldSet(
        version=GOLD_VERSION,
        labelled_by="author (not clinician-reviewed)",
        cases=[r.gold_case() for r in requisitions],
    )
    for index, r in enumerate(requisitions):
        write_case_pdf(r, out_dir / "pdfs" / f"{r.case_key}.pdf", seed=SEED + index)
    body = yaml.safe_dump(
        gold.model_dump(mode="json"), sort_keys=False, allow_unicode=True, width=100
    )
    (out_dir / "cases.yaml").write_text(HEADER + body)
    print(f"Wrote {len(requisitions)} cases to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
